fronhofer_info_gradient_invasions : fronhofer_info_gradient_invasions.cpp include/classes.h include/procedures.h
	g++ -Wall -g -o fronhofer_info_gradient_invasions fronhofer_info_gradient_invasions.cpp -lgsl -lgslcblas -lm
	
all:	fronhofer_info_gradient_invasions

clean:
	rm -f fronhofer_info_gradient_invasions
