fronhofer_gradient_invasions : fronhofer_gradient_invasions.cpp include/classes.h include/procedures.h
	g++ -Wall -g -o fronhofer_gradient_invasions fronhofer_gradient_invasions.cpp -lgsl -lgslcblas -lm

all:	fronhofer_gradient_invasions

clean:
	rm -f fronhofer_gradient_invasions
